export const styles = {
  image: {
    maxWidth: '100%',
    maxHeight: '150px',
    marginBottom: '10px',
  },
  editContainer: {
    padding: '10px',
  },
  nameInput: {
    width: '100%',
    padding: '8px',
    marginBottom: '10px',
    borderRadius: '4px',
    border: '1px solid #ccc',
    fontSize: '14px',
  },
  orderEditContainer: {
    marginBottom: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  orderInput: {
    width: '60px',
    padding: '6px',
    borderRadius: '4px',
    border: '1px solid #ccc',
    fontSize: '14px',
  },
  buttonGroup: {
    display: 'flex',
    gap: '12px',
    marginTop: '10px',
    width: '100%',
  },
  editButton: {
    flex: 1,
    padding: '6px 12px',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  deleteButton: {
    flex: 1,
    padding: '6px 12px',
    backgroundColor: '#bd2d2d',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  saveButton: {
    flex: 1,
    padding: '6px 12px',
    backgroundColor: '#37843a',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  cancelButton: {
    flex: 1,
    padding: '6px 12px',
    backgroundColor: '#9e9e9e',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  nameText: {
    display: 'block',
    marginBottom: '8px',
    fontSize: '14px',
    fontWeight: '500',
  },
  orderText: {
    display: 'block',
    marginBottom: '10px',
    fontSize: '14px',
    color: '#666',
  },
};
