export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
  },
  buttons: {
    display: 'flex',
    justifyContent: 'flex-end',
    margin: '10px',
  },
  logoutButton: {
    alignSelf: 'flex-end',
    padding: '10px 20px',
    margin: '10px',
    backgroundColor: 'blue',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  homeButton: {
    alignSelf: 'flex-end',
    padding: '10px 20px',
    margin: '10px',
    backgroundColor: 'green',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  categoryTabs: {
    display: 'flex',
    gap: '8px',
    margin: '0 10px 10px',
    flexWrap: 'wrap',
  },
  categoryTab: {
    padding: '8px 16px',
    backgroundColor: '#eee',
    color: '#333',
    border: '1px solid #ccc',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  categoryTabActive: {
    backgroundColor: '#0a0a0a',
    color: 'white',
    borderColor: '#0a0a0a',
  },
  syncing: {
    padding: '20px',
    color: '#666',
  },
  content: {
    display: 'flex',
    height: '100%',
    width: '100%',
  },
};
